spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springtx?useUnicode=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456